# Kubernetes Deployment Template
# TODO: Fill in the missing values

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: # TODO: Set number of replicas
  selector:
    matchLabels:
      app: # TODO: Match label
  template:
    metadata:
      labels:
        app: # TODO: Pod label
    spec:
      containers:
      - name: # TODO: Container name
        image: # TODO: Image name (e.g., nginx:alpine)
        ports:
        - containerPort: # TODO: Port number
